ALTER TRIGGER DD
ON DIEMDANH FOR INSERT
AS BEGIN
	BEGIN TRAN
	DECLARE @MaNV CHAR(10)
	SET @MaNV=(SELECT MaNV FROM INSERTED)
   	IF EXISTS (SELECT * FROM DIEMDANH WHERE MaNV=@MaNV AND CheckIn IS NOT NULL AND CheckOut IS NULL)
   	BEGIN
   		ROLLBACK TRAN
   		PRINT N' Check out thành công cho '+@MaNV
   		UPDATE DIEMDANH
   		SET
   			CheckOut=GETDATE() WHERE MaNV=@MaNV AND CheckIn IS NOT NULL AND CheckOut IS NULL	
   	END
   	ELSE IF not EXISTS (SELECT * FROM DIEMDANH WHERE MaNV=@MaNV AND CheckIn IS NOT NULL AND CheckOut IS NULL)
   	BEGIN
   		PRINT N' Check in thành công cho '+@MaNV
   		UPDATE DIEMDANH SET CheckIn=GETDATE() WHERE MaNV=@MaNV AND CheckIn IS NULL AND CheckOut IS NULL
   		COMMIT TRAN
   	END 
END
INSERT INTO DIEMDANH(MaNV) VALUES ('NV01')
SELECT
	d.MaNV,
	d.CheckIn,
	d.CheckOut,
	d.Cong
FROM
	DIEMDANH AS d
-- Trigger DIEMDANH
CREATE TRIGGER Cong
ON DIEMDANH FOR update
AS BEGIN
	DECLARE @x int
	SET @x=(SELECT DATEDIFF(HOUR,CheckIn,CheckOut) FROM DIEMDANH 
	        WHERE MaNV=(SELECT MaNV FROM INSERTED ) AND CheckOut=(SELECT CheckOut FROM INSERTED))
   	IF @x>7
   	UPDATE DIEMDANH SET Cong=1 WHERE MaNV=(SELECT MaNV FROM INSERTED ) AND CheckOut=(SELECT CheckOut FROM INSERTED)
   	ELSE IF @x>4 
   	UPDATE DIEMDANH SET Cong=0.5 WHERE MaNV=(SELECT MaNV FROM INSERTED ) AND CheckOut=(SELECT CheckOut FROM INSERTED)
   	ELSE 
   	UPDATE DIEMDANH SET Cong=0 WHERE MaNV=(SELECT MaNV FROM INSERTED ) AND CheckOut=(SELECT CheckOut FROM INSERTED)
END


